Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["C:/Users/jvinc/.ssh/id_rsa", "C:/Users/jvinc/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "C:/Users/jvinc/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"

  config.vm.network "private_network", ip: "192.168.33.40"

  config.vm.box = "rockylinux/8"
  config.vm.hostname = "rocky"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "rocky-8"
    vb.memory = 2048
    vb.cpus = 1
    vb.gui = true
    vb.check_guest_additions = false
  end

  config.vm.provision "shell", path: "comandos.sh"

end