Vagrant.configure("2") do |config|

  #---- Configurar llave SSH ----
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["C:/Users/jvinc/.ssh/id_rsa", "C:/Users/jvinc/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "C:/Users/jvinc/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"
  # config.ssh.username = "vagrant"
  # config.ssh.password = "vagrant"

  # ---- Provisionar archivo especifico ---- 
  # config.vm.provision "file", source: "./index.html", destination: "/home/vagrant/index.html"

  # ---- Configurar la Red ---- 
  config.vm.network "private_network", ip: "192.168.33.15"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3168 #2"

  # ---- Seleccionar Box (Sistema Operativo) ----
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "jenkins-master"
  config.vm.box_check_update = true

  # ---- Configurar la VM ---- 
  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian11-master"
    vb.memory = 2048
    vb.cpus = 2
    vb.gui = true
    vb.check_guest_additions = false
  end

  # ---- Sincronizar carpeta ---- 
  config.vm.synced_folder "./html", "/var/www/html/"

  # ---- Provisionar via archivo Bootstrap ---- 
  config.vm.provision "shell", path: "bootstrap.sh"

  # ---- Provisionar via Comandos Shell ---- 
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update -y
  #   apt-get install -y apache2
  # SHELL

end
