Vagrant.configure(2) do |config|
    config.ssh.insert_key = false
    config.ssh.private_key_path = ["C:/Users/jvinc/.ssh/id_rsa", "C:/Users/jvinc/.vagrant.d/insecure_private_key"]
    config.vm.provision "file", source: "C:/Users/jvinc/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"

    config.vm.box = "ubuntu/focal64"
    config.vm.box_check_update = true

    (1..3).each do |i|
        config.vm.network "private_network", ip: "192.168.33.1#{i}"
        config.vm.hostname = "ubuntuvm#{i}"
        config.vm.define "ubuntuvm#{i}" do |vb|
            config.vm.provider "virtualbox" do |vb|
                vb.name = "ubuntu2004vm#{i}"
                vb.memory = 2048
                vb.cpus = 2
                vb.gui = true
                vb.check_guest_additions = false
            end
        end
    end
end