  Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["C:/Users/jvinc/.ssh/id_rsa", "C:/Users/jvinc/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "C:/Users/jvinc/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/authorized_keys"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "ubuntu"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-20-04"
    vb.memory = 1024
    vb.cpus = 1
    vb.gui = false
    vb.check_guest_additions = true
  end

  config.vm.provision "shell", path: "bootstrap.sh"
  
end
  