Vagrant.configure("2") do |config|

  # ---- Seleccionar Box ---- https://app.vagrantup.com/ubuntu/boxes/
  config.vm.box = "ubuntu/trusty64"
  #config.vm.box_check_update = true

  # ---- Configurar la VM ---- 
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu_14_04"
    vb.cpus = "2"
    vb.memory = "1024"
    vb.gui = true
    vb.check_guest_additions = false
    # vb.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end

  # ---- Configurar la Red ---- 
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3168 #2"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # ---- Sincronizar carpeta ---- 
  # config.vm.synced_folder ".", "/var/www/html"

  # ---- Provisionar ---- 
  # config.vm.provision "shell", path: "bootstrap.sh"

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  # config.vm.provision "file", source: "./Dockerfile", destination: "/home/vagrant/Dockerfile"
end

  


