Vagrant.configure("2") do |config|
  
  # ---- Seleccionar Box ---- https://app.vagrantup.com/ubuntu/boxes/
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = true

  # ---- Configurar la VM ---- 
  config.vm.provider "virtualbox" do |vb|   
    vb.memory = 2048
    vb.name = "ubuntu_20_04"
    vb.check_guest_additions = false
    vb.cpus = 2
  end

  # ---- Configurar la Red ---- 
  config.vm.network "private_network", ip: "192.168.33.15"
  # config.vm.network "public_network", bridge: "Intel(R) Dual Band Wireless-AC 3168 #2"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # ---- Sincronizar carpeta ---- 
  config.vm.synced_folder ".", "/var/www/html"

  # ---- Provisionar ---- 
  config.vm.provision "shell", path: "bootstrap.sh"
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  config.vm.provision "file", source: "./Dockerfile", destination: "/home/vagrant/Dockerfile"
end